### ISSUE TITLE
What if this was a qc server and you want to replicate changes

### ISSUE THREAD

**Issue by shorif2000** [Sammaye/yii-audittrail#23]
I have made some modifications on the code to replicate all sql statements on to production server if this was a qc server etc.

<code>
 $k = aray();
            $v = array();

```
        foreach ($log->attributes as $key => $value) {
            if($key != "survey_id"){
                $k[] = "`$key`";
                $v[] = '"'.$value.'"';
            }
        }

        $sql = "INSERT INTO audit_trail (".implode(",",$k).") VALUES (".implode(",",$v).")";
        Yii::trace($sql);

        $connection_prod = \Yii::$app->db2;
        $transaction_prod = $connection_prod->beginTransaction();
        try {
            $connection_prod->createCommand($sql)->execute();

            if($transaction_prod->commit())
                return $log->save();
        }catch (Exception $e) {
            $transaction_prod->rollBack();
        }   
```

</code>

the above is placed in the `leavetrail` function

**Comment by Sammaye** [comment]
Since Yii already uses transactions it seems the easiest way to do this is to enable a `db` property within the behaviour which can then pick a db component.

**Comment by shorif2000** [comment]
not sure what you mean, can you provide example

**Comment by Sammaye** [comment]
I noticed the only difference in your code wass that you used a hardcoded connection `db2`.

So now in the model class you can actually specify a `db` param in the behaviour ad set it to `db2`.

``` php
function behaviors()
{
    return array(
        'loggable' => array('class' => '', 'db' => 'db2')
    );
}
```

and it will save there (note Yii1, if I remember right, uses transactions as default now so that part should be consistent).
